name:  Workflow_1
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Welcome message
        run: echo "My first GitHub Actions Job"
      - name: List files
        run: lsudo ls -la
      - name: Read file
        run: cat README.md