name: Install HTTPD Server

on: push

jobs:
  Install Apache2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: List Repo 
        run: ls -ltra
      - name: Execute Shell Script
        run: |
        chmod +x server.sh   
        ./server.sh  